sudo: required
services:
  - docker

before_install:
  - docker build -t beck/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run beck/react-test npm test -- --coverage

after_success:
  - docker build -t beck/multi-client ./client
  - docker build -t beck/multi-nginx ./nginx
  - docker build -t beck/multi-server ./server
  - docker build -t beck/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and pish them to the docker hub
  - docker push beck/multi-client
  - docker push beck/multi-nginx
  - docker push beck/multi-server
  - docker push beck/multi-worker
