sudo: required
services:
  - docker

before_install:
  - docker build -t beckdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true beckdocker/react-test npm test

after_success:
  - docker build -t beckdocker/multi-client ./client
  - docker build -t beckdocker/multi-nginx ./nginx
  - docker build -t beckdocker/multi-server ./server
  - docker build -t beckdocker/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and pish them to the docker hub
  - docker push beckdocker/multi-client
  - docker push beckdocker/multi-nginx
  - docker push beckdocker/multi-server
  - docker push beckdocker/multi-worker
